import "server-only";

import { SupabaseLearningTaskExecutionRepository } from "@amber/core";
import type { UserId } from "@amber/shared";
import type { Sql } from "postgres";
import { loadLearningWorkspace } from "./learning-workspace-server";

export interface LearningTaskReconciliationResult {
  readonly createdTaskIds: readonly string[];
  readonly existingTaskIds: readonly string[];
  readonly reusedOverlapTaskIds: readonly string[];
  readonly skippedProposalCount: number;
}

/** Explicit write boundary: concrete Learning proposals become canonical Tasks before reality is read. */
export async function reconcileLearningTasksForToday(input: {
  readonly sql: Sql;
  readonly userId: UserId;
  readonly today: string;
  readonly occurredAt?: Date;
}): Promise<LearningTaskReconciliationResult> {
  const workspace = await loadLearningWorkspace({ sql: input.sql, userId: input.userId, today: input.today });
  if (!workspace.configured) throw new Error(workspace.error ?? "Learning workspace를 불러오지 못했습니다.");
  const contexts = [...workspace.courses, ...workspace.certifications];
  const actions = contexts.flatMap((context) => context.actions);
  const existingTaskIds = actions.flatMap((action) => action.kind === "task" && action.taskId ? [action.taskId] : []);
  const repository = new SupabaseLearningTaskExecutionRepository(input.sql);
  const createdTaskIds: string[] = [];
  const reusedOverlapTaskIds: string[] = [];
  const seenMaterials = new Set<string>();
  let skippedProposalCount = 0;

  const materialize = async (action: (typeof actions)[number]): Promise<void> => {
    if (action.kind !== "proposal" || !action.proposal) return;
    if (seenMaterials.has(action.materialId)) {
      skippedProposalCount += 1;
      return;
    }
    seenMaterials.add(action.materialId);
    const result = await repository.materialize(input.userId, action.proposal, input.occurredAt);
    if (result.kind === "created") createdTaskIds.push(result.taskId);
    else if (result.kind === "existing") existingTaskIds.push(result.taskId);
    else reusedOverlapTaskIds.push(result.taskId);
  };

  for (const context of workspace.courses) {
    const proposals = context.actions.filter((action) => action.kind === "proposal" && action.proposal);
    if (context.actions.some((action) => action.kind === "task" && action.autoGenerated)) {
      skippedProposalCount += proposals.length;
      continue;
    }
    const next = proposals[0];
    if (next) await materialize(next);
    skippedProposalCount += Math.max(0, proposals.length - 1);
  }
  for (const context of workspace.certifications) {
    for (const action of context.actions) await materialize(action);
  }

  return {
    createdTaskIds,
    existingTaskIds: [...new Set(existingTaskIds)],
    reusedOverlapTaskIds: [...new Set(reusedOverlapTaskIds)],
    skippedProposalCount
  };
}
