import { describe, expect, it } from "vitest";
import type { LearningWorkspaceAction, LearningWorkspaceMaterial } from "./learning-workspace-types";
import { buildUniversityCourseReality, learningDetailExperience, selectUniversityCourses, summarizeUniversityCourses, universitySelfStudyLabel } from "./university-course-reality";

const material: LearningWorkspaceMaterial = {
  id: "material-1", title: "교안", stageId: null, materialType: "slides", unitType: "LESSON",
  totalUnits: 11, startUnit: null, state: "IN_PROGRESS", completedUnits: 6, totalScopedUnits: 11,
  progressPercent: 6 / 11 * 100, exposure: "학습 중", understanding: "기록 없음", validation: "미검증"
};
const nextTask: LearningWorkspaceAction = {
  kind: "task", taskId: "task-7", targetId: "target-7", learningUnitId: "unit-7", materialId: material.id,
  allocationPolicyId: null, title: "DB 교안 7강", assignedUnits: 1, startSequence: 7, endSequence: 7,
  policyName: null, source: "CANONICAL_TASK", reasons: [], estimatedMinutes: 30, proposal: null, autoGenerated: true
};
const units = Array.from({ length: 11 }, (_, index) => ({
  id: `unit-${index + 1}`, title: `${index + 1}주차`, materialId: material.id, sequenceNo: index + 1, unitType: "WEEK",
  exposureState: index < 6 ? "COMPLETE" as const : "NOT_STARTED" as const,
  understandingState: "UNKNOWN" as const,
  validationState: "NOT_TESTED" as const
}));

describe("University Course reality", () => {
  it("keeps school observation, exposure, understanding, and validation independent", () => {
    const reality = buildUniversityCourseReality({
      workContextId: "linked", snowboardCourseId: "89632", title: "Database", term: "2026-2",
      schoolProgress: { courseId: "89632", workContextId: "linked", completedLectureCount: 8,
        remainingLectureCount: 3, remainingLectureMinutes: 95, observedAt: new Date("2026-10-05T00:00:00Z") },
      materials: [material], units, nextAssessment: null, actions: [nextTask], hiddenLegacyContextIds: [], positionConfirmation: null
    });
    expect(reality.schoolProgress).toMatchObject({ completedLectureCount: 8, remainingLectureCount: 3 });
    expect(reality.selfStudy).toMatchObject({ completedUnits: 6, totalUnits: 11 });
    expect(reality.understanding).toEqual({ unknown: 11, weak: 0, ok: 0, strong: 0 });
    expect(reality.validation).toEqual({ notTested: 11, failed: 0, passed: 0 });
    expect(reality.gap).toEqual({ status: "unknown", unitsBehind: null });
    expect(reality.nextLearningTask).toEqual({ taskId: "task-7", title: "DB 교안 7강", estimatedMinutes: 30 });
    expect(reality.recommendedAction).toEqual({ learningUnitId: "unit-7", title: "DB 교안 7강", estimatedMinutes: 30 });
    expect(universitySelfStudyLabel(reality)).toBe("6주차");
  });

  it("does not fabricate a percentage when material scope has no denominator", () => {
    const reality = buildUniversityCourseReality({
      workContextId: "linked", snowboardCourseId: "89632", title: "Database", term: null,
      schoolProgress: null, materials: [{ ...material, completedUnits: 1, totalScopedUnits: null, progressPercent: null }],
      units: [units[0]!], nextAssessment: null, actions: [], hiddenLegacyContextIds: [], positionConfirmation: null,
      scopeActionUnavailableReason: "COURSE_RECIPE_MISSING"
    });
    expect(reality.selfStudy).toMatchObject({ completedUnits: 1, totalUnits: null, progressPercent: null });
    expect(reality.scopeActionUnavailableReason).toBe("COURSE_RECIPE_MISSING");
    expect(reality.understanding.unknown).toBe(1);
    expect(reality.validation.notTested).toBe(1);
  });

  it("uses the action-aware projection instead of requiring exactly one Material", () => {
    const recipeMaterials = ["lecture", "handout", "sql_problem"].map((actionKey) => ({
      ...material,
      id: `material-${actionKey}`,
      title: actionKey,
      completedUnits: actionKey === "sql_problem" ? 0 : 1,
      totalScopedUnits: 1
    }));
    const recipeUnits = recipeMaterials.map((item, index) => ({
      id: `unit-${item.id}`,
      title: "5주차",
      materialId: item.id,
      sequenceNo: 5,
      unitType: "WEEK",
      exposureState: index < 2 ? "COMPLETE" as const : "NOT_STARTED" as const,
      understandingState: index === 2 ? "WEAK" as const : "UNKNOWN" as const,
      validationState: index === 0 ? "PASSED" as const : "NOT_TESTED" as const
    }));
    const actions = ["lecture", "handout", "sql_problem"].map((actionKey, index) => ({
      learningUnitId: `unit-material-${actionKey}`,
      materialId: `material-${actionKey}`,
      actionKey,
      label: actionKey,
      phase: "BASE" as const,
      order: index + 1,
      requiredForBaseCompletion: true,
      exposure: index < 2 ? "COMPLETE" as const : "NOT_STARTED" as const,
      understanding: index === 2 ? "WEAK" as const : "UNKNOWN" as const,
      validation: index === 0 ? "PASSED" as const : "NOT_TESTED" as const
    }));
    const recipeProposal: LearningWorkspaceAction = {
      ...nextTask,
      kind: "proposal",
      taskId: null,
      targetId: null,
      learningUnitId: "unit-material-sql_problem",
      materialId: "material-sql_problem",
      title: "Database 5주차 SQL / 문제풀이",
      proposal: null
    };
    const reality = buildUniversityCourseReality({
      workContextId: "linked", snowboardCourseId: "89632", title: "Database", term: "2026-2",
      schoolProgress: null, materials: recipeMaterials, units: recipeUnits, nextAssessment: null, actions: [recipeProposal],
      hiddenLegacyContextIds: [], positionConfirmation: null,
      recipeBaseActions: actions.map(({ actionKey, label, order }) => ({ actionKey, label, order })),
      recipeProjection: { status: "PROJECTED", scopes: [{ scopeKey: "week:05", scopeLabel: "5주차", scopeType: "WEEK",
        sequence: 5, actions, baseState: "IN_PROGRESS" }] }
    });
    expect(reality.selfStudy).toMatchObject({
      state: "IN_PROGRESS", scopeStatus: "READY", completedUnits: 2, totalUnits: 3, currentPositionLabel: "5주차", materialId: null
    });
    expect(reality.scopeActionProgress).toMatchObject({ status: "PROJECTED" });
    expect(reality.recipeBaseActions.map((action) => action.actionKey)).toEqual(["lecture", "handout", "sql_problem"]);
    expect(reality.recommendedAction?.learningUnitId).toBe("unit-material-sql_problem");
    expect(reality.understanding).toEqual({ unknown: 2, weak: 1, ok: 0, strong: 0 });
    expect(reality.validation).toEqual({ notTested: 2, failed: 0, passed: 1 });
  });

  it("treats an empty scope as an unknown denominator", () => {
    const reality = buildUniversityCourseReality({
      workContextId: "linked", snowboardCourseId: "89632", title: "Database", term: null,
      schoolProgress: null, materials: [{ ...material, completedUnits: 0, totalScopedUnits: 0, progressPercent: null }],
      units: [], nextAssessment: null, actions: [], hiddenLegacyContextIds: [], positionConfirmation: null
    });
    expect(reality.selfStudy).toMatchObject({ completedUnits: 0, totalUnits: null, progressPercent: null });
  });

  it("shows only current-term Snowboard Courses and deterministically suppresses legacy section-title duplicates", () => {
    const courses = [
      { id: "legacy", title: "Database", term: "2026-2" },
      { id: "linked", title: "Database (002)", term: "2026-2" },
      { id: "other-linked", title: "Algorithms (001)", term: "2026-2" },
      { id: "old-linked", title: "Operating Systems (001)", term: "2025-2" },
      { id: "ambiguous", title: "Local Course", term: "local" }
    ];
    const result = selectUniversityCourses(courses, [
      { courseId: "89632", workContextId: "linked" },
      { courseId: "88860", workContextId: "other-linked" },
      { courseId: "70000", workContextId: "old-linked" }
    ]);
    expect(result.courses.map((course) => course.id)).toEqual(["other-linked", "linked"]);
    expect(result.courseIds.get("linked")).toBe("89632");
    expect(result.displayTitles.get("linked")).toBe("Database");
    expect(result.currentTerm).toBe("2026-2");
    expect(result.hiddenLegacyIds.get("linked")).toEqual(["legacy"]);
    expect(result.diagnostics).toEqual([
      { workContextId: "old-linked", title: "Operating Systems (001)", reason: "not_current_snowboard_course" },
      { workContextId: "legacy", title: "Database", reason: "legacy_duplicate" },
      { workContextId: "ambiguous", title: "Local Course", reason: "unlinked" }
    ]);
    expect(courses).toHaveLength(5);
  });

  it("chooses one stable display Course when current Snowboard sections normalize to one identity", () => {
    const courses = [
      { id: "section-2", title: "Database (002)", term: "2026-2" },
      { id: "section-1", title: "Database (001)", term: "2026-2" }
    ];
    const result = selectUniversityCourses(courses, [
      { courseId: "89098", workContextId: "section-2" },
      { courseId: "89097", workContextId: "section-1" }
    ]);
    expect(result.courses.map((course) => course.id)).toEqual(["section-1"]);
    expect(result.hiddenLegacyIds.get("section-1")).toEqual(["section-2"]);
    expect(result.diagnostics).toEqual([
      { workContextId: "section-2", title: "Database (002)", reason: "duplicate_snowboard_course" }
    ]);
  });

  it("reduces the observed 13 raw rows to six real current-term courses without deleting input", () => {
    const pairs = [
      ["AI시대의사고와의사소통", "AI시대의사고와의사소통 (036)"],
      ["데이터베이스", "데이터베이스 (002)"], ["모바일프로그래밍", "모바일프로그래밍 (001)"],
      ["알고리즘입문", "알고리즘입문 (001)"], ["인공지능입문", "인공지능입문 (003)"],
      ["프로그래밍방법론", "프로그래밍방법론 (001)"]
    ] as const;
    const courses = [
      ...pairs.flatMap(([legacy, linked], index) => [
        { id: `legacy-${index}`, title: legacy, term: "2026-2" },
        { id: `linked-${index}`, title: linked, term: "2026-2" }
      ]),
      { id: "sample", title: "샘플 과목", term: "local" }
    ];
    const result = selectUniversityCourses(courses, pairs.map((_, index) => ({
      courseId: String(88000 + index), workContextId: `linked-${index}`
    })));
    expect(courses).toHaveLength(13);
    expect(result.courses).toHaveLength(6);
    expect(result.diagnostics).toHaveLength(7);
    expect(result.diagnostics.filter((item) => item.reason === "legacy_duplicate")).toHaveLength(6);
    expect(result.diagnostics.find((item) => item.workContextId === "sample")?.reason).toBe("unlinked");
  });

  it("renders unknown self-study as unset rather than a fake zero", () => {
    const reality = buildUniversityCourseReality({
      workContextId: "linked", snowboardCourseId: "89632", title: "Database", term: "2026-2",
      schoolProgress: null, materials: [material], units: units.map((unit) => ({ ...unit, exposureState: "NOT_STARTED" as const })),
      nextAssessment: null, actions: [], hiddenLegacyContextIds: [], positionConfirmation: null
    });
    expect(universitySelfStudyLabel(reality)).toBe("현재 위치 미설정");
    expect(reality.selfStudy.progressPercent).toBeNull();
    expect(reality.selfStudy.initialized).toBe(false);
  });

  it("does not turn missing internal setup into a University warning count", () => {
    expect(summarizeUniversityCourses([
      { title: "Database", state: "unknown" },
      { title: "Algorithms", state: "normal" },
      { title: "AI", state: "risk" }
    ])).toEqual({ courseCount: 3, riskTitles: ["AI"] });
  });

  it("does not let Snowboard progress mutate personal Exposure", () => {
    const untouched = units.map((unit) => ({ ...unit, exposureState: "NOT_STARTED" as const }));
    const reality = buildUniversityCourseReality({
      workContextId: "linked", snowboardCourseId: "89632", title: "Database", term: "2026-2",
      schoolProgress: { courseId: "89632", workContextId: "linked", completedLectureCount: 8,
        remainingLectureCount: 3, remainingLectureMinutes: 95, observedAt: "2026-10-05T00:00:00Z" },
      materials: [material], units: untouched, nextAssessment: null, actions: [], hiddenLegacyContextIds: [], positionConfirmation: null
    });
    expect(reality.schoolProgress?.completedLectureCount).toBe(8);
    expect(reality.selfStudy.initialized).toBe(false);
    expect(untouched.every((unit) => unit.exposureState === "NOT_STARTED")).toBe(true);
  });

  it("keeps Certification on the existing Learning experience", () => {
    expect(learningDetailExperience("course")).toBe("university_reality");
    expect(learningDetailExperience("certification")).toBe("existing_learning");
  });
});
